### ISSUE TITLE
ErrorException in Safebrowsing.php line 84:

### ISSUE THREAD

**Issue by isurum** [snipe/Safebrowsing#3]
Hi!

I get the following Error when I try to call Safebrowsing::isFlagged('http://malware.testing.google.test/testing/malware/') method.

In my View I did add the following code.

<h5 class="url-title">{{ Safebrowsing::isFlagged('http://malware.testing.google.test/testing/malware/') }}</h5>

I got the following error.

ErrorException in Safebrowsing.php line 84:
Undefined property: Snipe\Safebrowsing\Safebrowsing::$results (View: C:\Users\Isuru\Documents\Source\url_shortner\resources\views\report.blade.php)

![download](https://cloud.githubusercontent.com/assets/1644255/24580148/9a3ea0c0-1720-11e7-8bb5-6f860c8a6aae.png)

**Comment by skibradshaw** [comment]
I get the same error:

PHP error:  Undefined property: Snipe\Safebrowsing\Safebrowsing::$results in /home/vagrant/Sites/at_apps/vendor/snipe/safebrowsing/src/Safebrowsing.php on line 84

**Comment by mrehayden1** [comment]
Proposed fix: https://github.com/snipe/Safebrowsing/pull/4

**Comment by robincsamuel** [comment]
I'm still facing this issue on `dev-master`. LIne 104.
